#!/bin/sh -f
# this script takes an input rootfile and dumps to screen the tree branches
# parameters

ARGS=1
if [ $# -lt "$ARGS" ]
# Test number of arguments to script (always a good idea).
then
  echo "Usage: `basename $0` <rootfile>  <nevts>    <nevts> is optional default=1"
  exit $E_BADARGS
fi
root_file=$1

#if [ ! -f "$root_file" ]
#then
#  echo "File \"$root_file\" does not exist."
#  exit $E_NOFILE
#fi  

NEVT=1
if [ $# -eq 2 ]
# Number of events to dump (default=1)
then
  NEVT=$2
fi

echo
echo ">>> Beginning cmsRun execution on `date`  <<<"
echo ">>> Rootfile: $root_file <<<"
echo ">>> Number of events: $NEVT <<<"
echo

#create config file
export WORKDIR=${PWD}
if [ -n "${CMS_PATH:-}" ]; then
  echo "CMSSW computing environment already setup"
else
#setup the environment
   echo "Setting up CMSSW computing environment"
   export PATH=/bin:/usr/bin:/usr/local/bin:/usr/krb5/bin:/usr/afsws/bin:/usr/krb5/bin/aklog:{$PATH}
   . /afs/fnal.gov/files/code/cms/setup/shrc uaf
   export SCRAM_ARCH=`scramv1 arch`
fi

cd $WORKDIR
pwd
eval `scramv1 runtime -sh`

cd ${WORKDIR}
export CFG=dumpit_${RANDOM}.cfg
cat > $CFG <<EOF
process Dump =  {
    #keep the logging output to a nice level
    include "FWCore/MessageLogger/data/MessageLogger.cfi"

    source = PoolSource {
	# untracked int32 maxEvents = ${NEVT}
	untracked vstring fileNames = {
	    #"file:${root_file}"
            "${root_file}"
            #"dcap://cmsdca.fnal.gov:24136/pnfs/fnal.gov/usr/cms/WAX/11/store/mc/2006/12/28/mc-onsel-120_PU_Photon_Jets_pt_120_170-DIGI-RECO-2/0000/92C84A71-C596-DB11-9476-00304875A7AF.root"
	}
    }

  untracked PSet maxEvents = {untracked int32 input = ${NEVT}}    
  module dump = EventContentAnalyzer {} 

  path p = { dump }
}
EOF
cmsRun -p ${WORKDIR}/${CFG}
rm $CFG
echo
echo ">>> Ending cmsRun execution on `date`  <<<"
echo
